// Каталог. Данные и фотографии взяты из Telegram-канала магазина.
// Чтобы добавить товар — дописать объект в PRODUCTS.
// images: первое фото показывается в карточке, остальные — в галерее.

export const CATEGORIES = [
  { id: "all", label: "Все" },
  { id: "ag", label: "Шиповки" },
  { id: "fg", label: "Бутсы" },
  { id: "tf", label: "Сороконожки" },
  { id: "gloves", label: "Перчатки" },
  { id: "balls", label: "Мячи" },
  { id: "kids", label: "Детям" },
];

export const PRODUCTS = [
  {
    id: "phantom-ag-2",
    title: "Nike Phantom",
    subtitle: "Шиповки · вторая расцветка",
    subtitleEn: "Turf boots · second colourway",
    category: "ag",
    price: 5990,
    sizes: ["39", "40", "41", "42", "43", "44", "45"],
    images: [
      "/catalog/phantom-ag-2-1.webp",
      "/catalog/phantom-ag-2-2.webp",
      "/catalog/phantom-ag-2-3.webp",
      "/catalog/phantom-ag-2-4.webp",
      "/catalog/phantom-ag-2-5.webp",
    ],
  },
  {
    id: "new-gen",
    title: "Nike",
    subtitle: "Новое поколение · шиповки и бутсы",
    subtitleEn: "New generation · turf and firm ground",
    category: "ag",
    price: 5990,
    badge: "Топ",
    badgeEn: "Top",
    note: "Шиповки 5990 ₽, бутсы этой же модели 6990 ₽",
    noteEn: "Turf 5990 ₽, firm ground version 6990 ₽",
    sizes: ["39", "40", "41", "42", "43", "44", "45"],
    images: [
      "/catalog/new-gen-1.webp",
      "/catalog/new-gen-2.webp",
      "/catalog/new-gen-3.webp",
      "/catalog/new-gen-4.webp",
    ],
  },
  {
    id: "puma-future-graffiti",
    title: "Puma Future",
    subtitle: "Шиповки · нового поколения",
    subtitleEn: "Turf boots · new generation",
    category: "ag",
    price: 6990,
    badge: "Хит",
    badgeEn: "Best seller",
    note: "Маломерят — берите на размер больше",
    noteEn: "Runs small — take one size up",
    sizes: ["39", "40", "41", "42", "43", "44", "45"],
    images: [
      "/catalog/puma-future-graffiti-1.webp",
      "/catalog/puma-future-graffiti-2.webp",
      "/catalog/puma-future-graffiti-3.webp",
    ],
  },
  {
    id: "phantom-ag",
    title: "Nike Phantom",
    subtitle: "Шиповки · одни из самых удобных",
    subtitleEn: "Turf boots · among the most comfortable",
    category: "ag",
    price: 5990,
    sizes: ["39", "40", "41", "42", "43", "44", "45"],
    images: [
      "/catalog/phantom-ag-1.webp",
      "/catalog/phantom-ag-2.webp",
      "/catalog/phantom-ag-3.webp",
    ],
  },
  {
    id: "puma-future-ag",
    title: "Puma Future",
    subtitle: "Шиповки · розовый / фиолетовый",
    subtitleEn: "Turf boots · pink / purple",
    category: "ag",
    price: 5990,
    sizes: ["39", "40", "41", "42", "43", "44", "45"],
    images: [
      "/catalog/puma-future-ag-1.webp",
      "/catalog/puma-future-ag-2.webp",
      "/catalog/puma-future-ag-3.webp",
    ],
  },
  {
    id: "soft-5990",
    title: "Nike",
    subtitle: "Шиповки · максимально мягкие",
    subtitleEn: "Turf boots · maximum softness",
    category: "ag",
    price: 5990,
    sizes: ["39", "40", "41", "42", "43", "44", "45"],
    images: [
      "/catalog/soft-5990-1.webp",
      "/catalog/soft-5990-2.webp",
    ],
  },
  {
    id: "phantom-bright",
    title: "Nike Phantom",
    subtitle: "Шиповки · яркая расцветка",
    subtitleEn: "Turf boots · bright colourway",
    category: "ag",
    price: 5990,
    sizes: ["39", "40", "41", "42", "43", "44", "45"],
    images: [
      "/catalog/phantom-bright-1.webp",
      "/catalog/phantom-bright-2.webp",
    ],
  },
  {
    id: "with-sock",
    title: "Nike",
    subtitle: "Шиповки с носком",
    subtitleEn: "Turf boots with collar",
    category: "ag",
    price: 5990,
    note: "Подходит практически под любую ногу",
    noteEn: "Fits almost any foot",
    sizes: ["35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45"],
    images: [
      "/catalog/with-sock-1.webp",
      "/catalog/with-sock-2.webp",
    ],
  },
  {
    id: "standout",
    title: "Nike",
    subtitle: "Шиповки · для любителей носка",
    subtitleEn: "Turf boots · for collar lovers",
    category: "ag",
    price: 5990,
    sizes: ["39", "40", "41", "42", "43", "44", "45"],
    images: [
      "/catalog/standout-1.webp",
      "/catalog/standout-2.webp",
    ],
  },
  {
    id: "air-zoom-fg",
    title: "Nike Air Zoom",
    subtitle: "Бутсы · фиолетовый",
    subtitleEn: "Firm ground · purple",
    category: "fg",
    price: 6990,
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43", "44", "45"],
    images: [
      "/catalog/air-zoom-fg-1.webp",
      "/catalog/air-zoom-fg-2.webp",
      "/catalog/air-zoom-fg-3.webp",
    ],
  },
  {
    id: "phantom-fg",
    title: "Nike Phantom",
    subtitle: "Бутсы · золотая классика",
    subtitleEn: "Firm ground · golden classic",
    category: "fg",
    price: 6990,
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43", "44", "45"],
    images: [
      "/catalog/phantom-fg-1.webp",
      "/catalog/phantom-fg-2.webp",
      "/catalog/phantom-fg-3.webp",
    ],
  },
  {
    id: "tiempo-fg",
    title: "Nike Tiempo",
    subtitle: "Бутсы · для тех, кто любит комфорт",
    subtitleEn: "Firm ground · built for comfort",
    category: "fg",
    price: 6990,
    sizes: ["39", "40", "41", "42", "43", "44", "45"],
    images: [
      "/catalog/tiempo-fg-1.webp",
      "/catalog/tiempo-fg-2.webp",
      "/catalog/tiempo-fg-3.webp",
    ],
  },
  {
    id: "tempo",
    title: "Nike Tiempo",
    subtitle: "Бутсы · классика",
    subtitleEn: "Firm ground · classic",
    category: "fg",
    price: 6990,
    sizes: ["39", "40", "41", "42", "43", "44", "45"],
    images: [
      "/catalog/tempo-1.webp",
      "/catalog/tempo-2.webp",
      "/catalog/tempo-3.webp",
    ],
  },
  {
    id: "air-zoom-small",
    title: "Nike Air Zoom",
    subtitle: "Бутсы · малые размеры",
    subtitleEn: "Firm ground · small sizes",
    category: "fg",
    price: 6990,
    sizes: ["35", "36", "37", "38"],
    images: [
      "/catalog/air-zoom-small-1.webp",
      "/catalog/air-zoom-small-2.webp",
      "/catalog/air-zoom-small-3.webp",
    ],
  },
  {
    id: "predator-fg",
    title: "Adidas Predator",
    subtitle: "Бутсы · классика",
    subtitleEn: "Firm ground · classic",
    category: "fg",
    price: 6990,
    sizes: ["39", "40", "41", "42", "43", "44", "45"],
    images: [
      "/catalog/predator-fg-1.webp",
      "/catalog/predator-fg-2.webp",
      "/catalog/predator-fg-3.webp",
    ],
  },
  {
    id: "tempo-retro",
    title: "Nike Tiempo",
    subtitle: "Бутсы · ностальгическая классика",
    subtitleEn: "Firm ground · nostalgic classic",
    category: "fg",
    price: 6990,
    note: "Последняя пара, только 40 размер",
    noteEn: "Last pair, size 40 only",
    sizes: ["40"],
    images: [
      "/catalog/tempo-retro-1.webp",
      "/catalog/tempo-retro-2.webp",
    ],
  },
  {
    id: "mizuno-1",
    title: "Mizuno",
    subtitle: "Очень мягкие · лучшие в своём классе",
    subtitleEn: "Very soft · best in class",
    category: "fg",
    price: 6990,
    sizes: ["39", "40", "41", "42", "43", "44", "45"],
    images: [
      "/catalog/mizuno-1-1.webp",
    ],
  },
  {
    id: "newbalance",
    title: "New Balance",
    subtitle: "Подходят под любую ногу",
    subtitleEn: "Fits any foot shape",
    category: "fg",
    price: 6990,
    sizes: ["39", "40", "41", "42", "43"],
    images: [
      "/catalog/newbalance-1.webp",
    ],
  },
  {
    id: "colorchange",
    title: "Меняют цвет от воды",
    subtitle: "Бутсы · реагируют на влагу",
    subtitleEn: "Firm ground · react to water",
    category: "fg",
    price: 6990,
    badge: "Необычное",
    badgeEn: "Unusual",
    sizes: ["39", "40", "41", "42", "43"],
    images: [
      "/catalog/colorchange-1.webp",
    ],
  },
  {
    id: "puma-future-tf",
    title: "Puma Future",
    subtitle: "Сороконожки · мягче для коленей",
    subtitleEn: "Astro turf · easier on the knees",
    category: "tf",
    price: 5990,
    note: "Хороший вариант, если чувствуются нагрузки на колени",
    noteEn: "Good choice if your knees feel the load",
    sizes: ["39", "40", "41", "42", "43", "44", "45"],
    images: [
      "/catalog/puma-future-tf-1.webp",
      "/catalog/puma-future-tf-2.webp",
      "/catalog/puma-future-tf-3.webp",
    ],
  },
  {
    id: "mizuno-2",
    title: "Mizuno",
    subtitle: "Сороконожки · бирюзовый",
    subtitleEn: "Astro turf · turquoise",
    category: "tf",
    price: 6990,
    sizes: ["39", "40", "41", "42", "43", "44", "45"],
    images: [
      "/catalog/mizuno-2-1.webp",
    ],
  },
  {
    id: "gloves-blago-3",
    title: "Перчатки BLAGO",
    subtitle: "Разные расцветки · немецкий латекс",
    subtitleEn: "Various colourways · German latex",
    category: "gloves",
    price: 5990,
    badge: "1+1",
    badgeEn: "1+1",
    note: "При покупке одной пары вторая в подарок",
    noteEn: "Buy one pair, get a second free",
    sizes: ["8", "9", "10"],
    images: [
      "/catalog/gloves-blago-3-1.webp",
      "/catalog/gloves-blago-3-2.webp",
      "/catalog/gloves-blago-3-3.webp",
      "/catalog/gloves-blago-3-4.webp",
      "/catalog/gloves-blago-3-5.webp",
      "/catalog/gloves-blago-3-6.webp",
      "/catalog/gloves-blago-3-7.webp",
      "/catalog/gloves-blago-3-8.webp",
      "/catalog/gloves-blago-3-9.webp",
      "/catalog/gloves-blago-3-10.webp",
    ],
  },
  {
    id: "gloves-blago-2",
    title: "Перчатки BLAGO",
    subtitle: "Вратарские · базовая модель",
    subtitleEn: "Goalkeeper · base model",
    category: "gloves",
    price: 5000,
    sizes: ["8", "9", "10"],
    images: [
      "/catalog/gloves-blago-2-1.webp",
      "/catalog/gloves-blago-2-2.webp",
      "/catalog/gloves-blago-2-3.webp",
      "/catalog/gloves-blago-2-4.webp",
      "/catalog/gloves-blago-2-5.webp",
      "/catalog/gloves-blago-2-6.webp",
    ],
  },
  {
    id: "gloves-blago-1",
    title: "Перчатки BLAGO",
    subtitle: "Немецкий латекс 4 мм · плотная посадка",
    subtitleEn: "German latex 4 mm · snug fit",
    category: "gloves",
    price: 6000,
    sizes: ["8", "9", "10"],
    images: [
      "/catalog/gloves-blago-1-1.webp",
      "/catalog/gloves-blago-1-2.webp",
      "/catalog/gloves-blago-1-3.webp",
      "/catalog/gloves-blago-1-4.webp",
      "/catalog/gloves-blago-1-5.webp",
    ],
  },
  {
    id: "ball-fifa",
    title: "Мяч Adidas, оригинал",
    subtitle: "Чемпионат мира 2026 · FIFA",
    subtitleEn: "World Cup 2026 · FIFA",
    category: "balls",
    price: 14500,
    note: "При покупке — два мяча в подарок",
    noteEn: "Two extra balls included",
    sizes: ["ONE"],
    images: [
      "/catalog/ball-fifa-1.webp",
      "/catalog/ball-fifa-2.webp",
      "/catalog/ball-fifa-3.webp",
      "/catalog/ball-fifa-4.webp",
      "/catalog/ball-fifa-5.webp",
      "/catalog/ball-fifa-6.webp",
    ],
  },
  {
    id: "ball-demix",
    title: "Мяч Demix",
    subtitle: "Второй мяч в подарок",
    subtitleEn: "Second ball free",
    category: "balls",
    price: 5990,
    badge: "1+1",
    badgeEn: "1+1",
    sizes: ["ONE"],
    images: [
      "/catalog/ball-demix-1.webp",
      "/catalog/ball-demix-2.webp",
      "/catalog/ball-demix-3.webp",
      "/catalog/ball-demix-4.webp",
      "/catalog/ball-demix-5.webp",
      "/catalog/ball-demix-6.webp",
    ],
  },
  {
    id: "body-kids",
    title: "Детское боди",
    subtitle: "Клубные расцветки",
    subtitleEn: "Club colourways",
    category: "kids",
    price: 1000,
    sizes: ["ONE"],
    images: [
      "/catalog/body-kids-1.webp",
      "/catalog/body-kids-2.webp",
      "/catalog/body-kids-3.webp",
      "/catalog/body-kids-4.webp",
      "/catalog/body-kids-5.webp",
      "/catalog/body-kids-6.webp",
      "/catalog/body-kids-7.webp",
      "/catalog/body-kids-8.webp",
      "/catalog/body-kids-9.webp",
      "/catalog/body-kids-10.webp",
      "/catalog/body-kids-11.webp",
      "/catalog/body-kids-12.webp",
    ],
  },
];

export const formatPrice = (value) =>
  new Intl.NumberFormat("ru-RU", {
    style: "currency",
    currency: "RUB",
    maximumFractionDigits: 0,
  }).format(value);
